#pragma checksum "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "efe9f1540f577bf7b3f8a4a4e14ac6f9e497b565"
// <auto-generated/>
#pragma warning disable 1591
namespace ManPowerWeb.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerWeb;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerWeb.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 11 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Radzen.Blazor;

#line default
#line hidden
#nullable disable
#nullable restore
#line 12 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using CurrieTechnologies.Razor.SweetAlert2;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
using ManPowerCore.Common;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
using ManPowerCore.Controller;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
using ManPowerCore.Domain;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
using ManPowerWeb.Model;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
using System.Text.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 11 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
using Radzen;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/DME37Search")]
    public partial class DME37Search : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "main");
            __builder.AddMarkupContent(2, "\r\n\r\n    ");
            __builder.OpenComponent<Radzen.Blazor.RadzenCard>(3);
            __builder.AddAttribute(4, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(5, "\r\n        ");
                __builder2.AddMarkupContent(6, "<div class=\"wizard-heading\">DME 37</div>\r\n\r\n        \r\n\r\n        ");
                __builder2.OpenElement(7, "div");
                __builder2.AddAttribute(8, "class", "row");
                __builder2.AddAttribute(9, "style", "margin-left:6px");
                __builder2.AddMarkupContent(10, "\r\n            ");
                __builder2.OpenElement(11, "div");
                __builder2.AddAttribute(12, "class", "col-6");
                __builder2.AddMarkupContent(13, "\r\n                ");
                __builder2.OpenElement(14, "div");
                __builder2.AddAttribute(15, "class", "row");
                __builder2.AddMarkupContent(16, "\r\n                    ");
                __builder2.OpenElement(17, "div");
                __builder2.AddAttribute(18, "class", "col-3");
                __builder2.AddMarkupContent(19, "\r\n                        ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenLabel>(20);
                __builder2.AddAttribute(21, "Text", "Year");
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(22, "\r\n                    ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(23, "\r\n                    ");
                __builder2.OpenElement(24, "div");
                __builder2.AddAttribute(25, "class", "col-7");
                __builder2.AddMarkupContent(26, "\r\n                            ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenTextBox>(27);
                __builder2.AddAttribute(28, "Class", "w-100");
                __builder2.AddAttribute(29, "Placeholder", "");
                __builder2.AddAttribute(30, "Name", "year");
                __builder2.AddAttribute(31, "Style", "margin-bottom:10px;font-size:0.9em; display: block");
                __builder2.AddAttribute(32, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>(
#nullable restore
#line 31 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                      year

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(33, "ValueChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => year = __value, year))));
                __builder2.AddAttribute(34, "ValueExpression", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Linq.Expressions.Expression<System.Func<System.String>>>(() => year));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(35, "\r\n                            \r\n                    ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(36, "\r\n                ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(37, "\r\n                <br>\r\n\r\n            ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(38, "\r\n        ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(39, "\r\n\r\n\r\n\r\n        ");
                __builder2.OpenElement(40, "div");
                __builder2.AddAttribute(41, "class", "col-6");
                __builder2.AddMarkupContent(42, "\r\n            ");
                __builder2.OpenElement(43, "div");
                __builder2.AddAttribute(44, "class", "row");
                __builder2.AddAttribute(45, "style", "margin-left:-3px");
                __builder2.AddMarkupContent(46, "\r\n                ");
                __builder2.OpenElement(47, "div");
                __builder2.AddAttribute(48, "class", "col-3");
                __builder2.AddMarkupContent(49, "\r\n                    ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenLabel>(50);
                __builder2.AddAttribute(51, "Text", "Position");
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(52, "\r\n                ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(53, "\r\n                ");
                __builder2.OpenElement(54, "div");
                __builder2.AddAttribute(55, "class", "col-7");
                __builder2.AddMarkupContent(56, "\r\n                        ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenTextBox>(57);
                __builder2.AddAttribute(58, "Class", "w-100");
                __builder2.AddAttribute(59, "Placeholder", "");
                __builder2.AddAttribute(60, "Name", "possition");
                __builder2.AddAttribute(61, "TextProperty", "monthName");
                __builder2.AddAttribute(62, "Style", "margin-bottom:10px;font-size:0.9em; display: block");
                __builder2.AddAttribute(63, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>(
#nullable restore
#line 50 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                   position

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(64, "ValueChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => position = __value, position))));
                __builder2.AddAttribute(65, "ValueExpression", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Linq.Expressions.Expression<System.Func<System.String>>>(() => position));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(66, "\r\n                    ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenRequiredValidator>(67);
                __builder2.AddAttribute(68, "Component", "possition");
                __builder2.AddAttribute(69, "Text", "Possition is required");
                __builder2.AddAttribute(70, "Style", "position: absolute");
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(71, "\r\n                ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(72, "\r\n            ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(73, "\r\n        ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(74, "\r\n        <br>\r\n\r\n\r\n        ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenButton>(75);
                __builder2.AddAttribute(76, "Shade", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.Shade>(
#nullable restore
#line 58 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                             Shade.Darker

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(77, "Text", "Search");
                __builder2.AddAttribute(78, "ButtonStyle", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.ButtonStyle>(
#nullable restore
#line 58 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                      ButtonStyle.Secondary

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(79, "Click", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 58 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                    () => Search(year,position)

#line default
#line hidden
#nullable disable
                )));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(80, "\r\n\r\n        <br><br>\r\n\r\n\r\n        ");
                __builder2.OpenElement(81, "a");
                __builder2.AddAttribute(82, "href", "/DME37");
                __builder2.AddMarkupContent(83, "\r\n            ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenButton>(84);
                __builder2.AddAttribute(85, "Shade", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.Shade>(
#nullable restore
#line 64 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                 Shade.Darker

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(86, "Text", "Add Vacancy");
                __builder2.AddAttribute(87, "ButtonStyle", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.ButtonStyle>(
#nullable restore
#line 64 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                               ButtonStyle.Secondary

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(88, "Style", "width:170px;");
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(89, "\r\n        ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(90, "\r\n\r\n        <br><br><br><br>\r\n\r\n\r\n\r\n        ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenDataGrid<CompanyVecansyRegistationDetails>>(91);
                __builder2.AddAttribute(92, "Style", "width: 1000px");
                __builder2.AddAttribute(93, "AllowFiltering", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                              true

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(94, "AllowColumnResize", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                       true

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(95, "AllowAlternatingRows", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                   false

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(96, "FilterMode", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.FilterMode>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                      FilterMode.Advanced

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(97, "AllowSorting", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                                                         true

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(98, "PageSize", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Int32>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                                                                         5

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(99, "AllowPaging", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                                                                                         true

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(100, "PagerHorizontalAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.HorizontalAlign>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                                                                                                                     HorizontalAlign.Left

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(101, "ShowPagingSummary", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 71 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                                                                                                                                                              true

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(102, "Data", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Collections.Generic.IEnumerable<CompanyVecansyRegistationDetails>>(
#nullable restore
#line 72 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                               cc

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(103, "ColumnWidth", "300px");
                __builder2.AddAttribute(104, "LogicalFilterOperator", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.LogicalFilterOperator>(
#nullable restore
#line 72 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                       LogicalFilterOperator.Or

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(105, "Columns", (Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(106, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(107);
                    __builder3.AddAttribute(108, "Property", "Date");
                    __builder3.AddAttribute(109, "Filterable", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 76 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                           false

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(110, "Title", "Date");
                    __builder3.AddAttribute(111, "Frozen", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 76 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                       true

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(112, "Width", "150px");
                    __builder3.AddAttribute(113, "TextAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.TextAlign>(
#nullable restore
#line 76 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                                                                      TextAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(114, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(115);
                    __builder3.AddAttribute(116, "Property", "Address");
                    __builder3.AddAttribute(117, "Title", "Address");
                    __builder3.AddAttribute(118, "Frozen", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 77 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
                                                                                                                          true

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(119, "Width", "200px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(120, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(121);
                    __builder3.AddAttribute(122, "Property", "WebSiteLink");
                    __builder3.AddAttribute(123, "Title", "WebSiteLink");
                    __builder3.AddAttribute(124, "Width", "160px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(125, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(126);
                    __builder3.AddAttribute(127, "Property", "BusinessRegistationNumber");
                    __builder3.AddAttribute(128, "Title", "BRN");
                    __builder3.AddAttribute(129, "Width", "120px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(130, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(131);
                    __builder3.AddAttribute(132, "Property", "JobPosition");
                    __builder3.AddAttribute(133, "Title", "JobPosition");
                    __builder3.AddAttribute(134, "Width", "170px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(135, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(136);
                    __builder3.AddAttribute(137, "Property", "CareerPath");
                    __builder3.AddAttribute(138, "Title", "Career Path");
                    __builder3.AddAttribute(139, "FormatString", "{0:d}");
                    __builder3.AddAttribute(140, "Width", "150px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(141, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(142);
                    __builder3.AddAttribute(143, "Property", "Levels");
                    __builder3.AddAttribute(144, "Title", "Level");
                    __builder3.AddAttribute(145, "FormatString", "{0:d}");
                    __builder3.AddAttribute(146, "Width", "100px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(147, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(148);
                    __builder3.AddAttribute(149, "Property", "SalaryLevel");
                    __builder3.AddAttribute(150, "Title", "SalaryLevel");
                    __builder3.AddAttribute(151, "Width", "150px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(152, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(153);
                    __builder3.AddAttribute(154, "Property", "NumberOfVacancy");
                    __builder3.AddAttribute(155, "Title", "Number Of Vacancy");
                    __builder3.AddAttribute(156, "Width", "200px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(157, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(158);
                    __builder3.AddAttribute(159, "Property", "Name");
                    __builder3.AddAttribute(160, "Title", "Name");
                    __builder3.AddAttribute(161, "Width", "200px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(162, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(163);
                    __builder3.AddAttribute(164, "Property", "Position");
                    __builder3.AddAttribute(165, "Title", "Position");
                    __builder3.AddAttribute(166, "Width", "150px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(167, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(168);
                    __builder3.AddAttribute(169, "Property", "ContactNumber");
                    __builder3.AddAttribute(170, "Title", "Contact Number");
                    __builder3.AddAttribute(171, "Width", "180px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(172, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(173);
                    __builder3.AddAttribute(174, "Property", "WhatsappNumber");
                    __builder3.AddAttribute(175, "Title", "Whatsapp Number");
                    __builder3.AddAttribute(176, "Width", "180px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(177, "\r\n                ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<CompanyVecansyRegistationDetails>>(178);
                    __builder3.AddAttribute(179, "Property", "Email");
                    __builder3.AddAttribute(180, "Title", "Email");
                    __builder3.AddAttribute(181, "Width", "220px");
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(182, "\r\n\r\n            ");
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(183, "\r\n\r\n        <br><br>\r\n\r\n          \r\n    ");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(184, "\r\n\r\n");
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 105 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\DME37Search.razor"
       


    public string year = "";

    public string position = "";


    List<CompanyVecansyRegistationDetails> cc = new List<CompanyVecansyRegistationDetails>();

   

    void Search(string y, string p)
    {
        CompanyVecansyRegistationDetails companyVecansyRegistationDetails = new CompanyVecansyRegistationDetails();
        CompanyVecansyRegistationDetailsController companyVecansyRegistationDetailsController = ControllerFactory.CreateCompanyVecansyRegistationDetailsController();

        cc = companyVecansyRegistationDetailsController.GetAllCompanyVecansyRegistationDetails(p,y);
    
    }


    void OnInvalidSubmit(FormInvalidSubmitEventArgs args)
    {
        // console.Log($"InvalidSubmit: {JsonSerializer.Serialize(args, new JsonSerializerOptions() {  WriteIndented = true })}");
    }





#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private DialogService DialogService { get; set; }
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private IJSRuntime JSRuntime { get; set; }
    }
}
#pragma warning restore 1591
