#pragma checksum "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "bd860438062b5a62cc1f65320b5829a4dffb634d"
// <auto-generated/>
#pragma warning disable 1591
namespace ManPowerWeb.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerWeb;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerWeb.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Radzen;

#line default
#line hidden
#nullable disable
#nullable restore
#line 11 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using Radzen.Blazor;

#line default
#line hidden
#nullable disable
#nullable restore
#line 12 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using CurrieTechnologies.Razor.SweetAlert2;

#line default
#line hidden
#nullable disable
#nullable restore
#line 13 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerCore.Common;

#line default
#line hidden
#nullable disable
#nullable restore
#line 14 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerCore.Domain;

#line default
#line hidden
#nullable disable
#nullable restore
#line 15 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\_Imports.razor"
using ManPowerCore.Controller;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/anualTargetRecommondation")]
    public partial class AnnualTargetRecommondation : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "main");
            __builder.AddMarkupContent(2, "\r\n    ");
            __builder.OpenComponent<Radzen.Blazor.RadzenCard>(3);
            __builder.AddAttribute(4, "Style", "padding-left:45px;");
            __builder.AddAttribute(5, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(6, "\r\n        ");
                __builder2.AddMarkupContent(7, "<div class=\"wizard-heading\">Annual Targets Recommondation</div>\r\n        \r\n\r\n        \r\n");
#nullable restore
#line 11 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
             foreach (var i in programTargetsList.Where(u => u.IsRecommended == 1))
            {
                myList.Add(i);
            }

#line default
#line hidden
#nullable disable
                __builder2.AddContent(8, "            ");
                __builder2.OpenComponent<Radzen.Blazor.RadzenDataGrid<ProgramTarget>>(9);
                __builder2.AddAttribute(10, "Data", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Collections.Generic.IEnumerable<ProgramTarget>>(
#nullable restore
#line 15 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                         myList

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(11, "EmptyTemplate", (Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(12, "\r\n                    ");
                    __builder3.AddMarkupContent(13, "<p style=\"color: lightgrey; font-size: 24px; text-align: center; margin: 2rem;\">No records to display.</p>\r\n                ");
                }
                ));
                __builder2.AddAttribute(14, "Columns", (Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(15, "\r\n                    ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<ProgramTarget>>(16);
                    __builder3.AddAttribute(17, "Property", "ProgramTargetId");
                    __builder3.AddAttribute(18, "Title", "ID");
                    __builder3.AddAttribute(19, "Width", "90px");
                    __builder3.AddAttribute(20, "TextAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.TextAlign>(
#nullable restore
#line 20 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                              TextAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(21, "\r\n                    ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<ProgramTarget>>(22);
                    __builder3.AddAttribute(23, "Property", "TargetYear");
                    __builder3.AddAttribute(24, "Title", "Year");
                    __builder3.AddAttribute(25, "Width", "150px");
                    __builder3.AddAttribute(26, "TextAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.TextAlign>(
#nullable restore
#line 21 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                            TextAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(27, "\r\n                    ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<ProgramTarget>>(28);
                    __builder3.AddAttribute(29, "Property", "TargetMonth");
                    __builder3.AddAttribute(30, "Title", "Month");
                    __builder3.AddAttribute(31, "Width", "150px");
                    __builder3.AddAttribute(32, "TextAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.TextAlign>(
#nullable restore
#line 22 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                              TextAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(33, "\r\n                    ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<ProgramTarget>>(34);
                    __builder3.AddAttribute(35, "Property", "Title");
                    __builder3.AddAttribute(36, "Title", "Project");
                    __builder3.AddAttribute(37, "Width", "170px");
                    __builder3.AddAttribute(38, "TextAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.TextAlign>(
#nullable restore
#line 23 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                          TextAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(39, "\r\n                    ");
                    __builder3.OpenComponent<Radzen.Blazor.RadzenDataGridColumn<ProgramTarget>>(40);
                    __builder3.AddAttribute(41, "Title", "Action");
                    __builder3.AddAttribute(42, "Width", "200px");
                    __builder3.AddAttribute(43, "TextAlign", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.TextAlign>(
#nullable restore
#line 24 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                        TextAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(44, "Template", (Microsoft.AspNetCore.Components.RenderFragment<ProgramTarget>)((myList) => (__builder4) => {
                        __builder4.AddMarkupContent(45, "\r\n                            ");
                        __builder4.OpenComponent<Radzen.Blazor.RadzenButton>(46);
                        __builder4.AddAttribute(47, "Shade", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.Shade>(
#nullable restore
#line 26 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                 Shade.Lighter

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddAttribute(48, "ButtonStyle", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.ButtonStyle>(
#nullable restore
#line 26 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                             ButtonStyle.Success

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddAttribute(49, "Text", "View");
                        __builder4.AddAttribute(50, "Size", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Radzen.ButtonSize>(
#nullable restore
#line 26 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                    ButtonSize.Medium

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddAttribute(51, "Click", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 26 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                                              () => navigateToView(myList.ProgramTargetId)

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddEventStopPropagationAttribute(52, "onclick", 
#nullable restore
#line 26 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
                                                                                                                                                                                                                      true

#line default
#line hidden
#nullable disable
                        );
                        __builder4.AddAttribute(53, "Style", "width:80px;");
                        __builder4.CloseComponent();
                        __builder4.AddMarkupContent(54, "\r\n                        ");
                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(55, "\r\n                ");
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(56, "\r\n        \r\n    ");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(57, "\r\n");
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 35 "D:\SLIIT\Intern bellwantage\Man Power 2\ManPowerWeb\Pages\AnnualTargetRecommondation.razor"
       
    string[] form = { "DME 21", "DME 22" };
    private int status;
    private List<DME21Model> dme = new List<DME21Model>();
    private bool isClicked = false;
    private int count;
    private string statusName;

    List<Month> monthTable = new List<Month>();
    ProgramTarget programTarget = new ProgramTarget();
    List<ProgramTarget> searchTarget = new List<ProgramTarget>();
    ProgramAssignee programAssignee = new ProgramAssignee();
    List<DepartmentUnit> listDistrict = new List<DepartmentUnit>();
    List<DepartmentUnit> listDSDivision = new List<DepartmentUnit>();
    List<Designation> listDesignation = new List<Designation>();
    List<ProgramType> listProgramType = new List<ProgramType>();
    List<DepartmentUnitPositions> listUser = new List<DepartmentUnitPositions>();
    List<SystemUser> listUsers = new List<SystemUser>();
    List<ManPowerCore.Domain.Program> program = new List<ManPowerCore.Domain.Program>();
    List<ProgramTarget> programTargetsList = new List<ProgramTarget>();
    List<ProgramTarget> myList = new List<ProgramTarget>();
    List<ProgramAssignee> assignees = new List<ProgramAssignee>();

    protected override void OnInitialized()
    {
        base.OnInitialized();

        monthTable.Add(new Month() { monthName = "January", monthNumber = 1 });
        monthTable.Add(new Month() { monthName = "February", monthNumber = 2 });
        monthTable.Add(new Month() { monthName = "March", monthNumber = 3 });
        monthTable.Add(new Month() { monthName = "April", monthNumber = 4 });
        monthTable.Add(new Month() { monthName = "May", monthNumber = 5 });
        monthTable.Add(new Month() { monthName = "June", monthNumber = 6 });
        monthTable.Add(new Month() { monthName = "July", monthNumber = 7 });
        monthTable.Add(new Month() { monthName = "August", monthNumber = 8 });
        monthTable.Add(new Month() { monthName = "September", monthNumber = 9 });
        monthTable.Add(new Month() { monthName = "October", monthNumber = 10 });
        monthTable.Add(new Month() { monthName = "November", monthNumber = 11 });
        monthTable.Add(new Month() { monthName = "December", monthNumber = 12 });


        ProgramTargetController programTargetController = ControllerFactory.CreateProgramTargetController();
        programTargetsList = programTargetController.GetAllProgramTarget(true, true, true, true);

        ProgramAssigneeController programAssigneeController = ControllerFactory.CreateProgramAssigneeController();
        assignees = programAssigneeController.GetAllProgramAssignee(true, true, true);
    }

    async Task navigateToView(int index)
    {
        NavigationManager.NavigateTo($"/anualTargetRecommondation/target/{index}");
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private NavigationManager NavigationManager { get; set; }
    }
}
#pragma warning restore 1591
